# global default
container:
  image: node:latest

lint_task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package.json
    populate_script: npm install

  test_script: npm run lint

test_task:
  container:
    matrix:
      image: node:latest
      image: node:8.11.0

  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package.json
    populate_script: npm install

  test_script: npm run test


